version: '3'

services:

  mysql-development:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_DATABASE: storage
    cap_add:
      - SYS_NICE
    ports:
      - "3306:3306"