version: '3'

services:

  mysql-development:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "senhasenha@123"
      MYSQL_DATABASE: storage
    cap_add:
      - SYS_NICE
    ports:
      - "3306:3306"